version: "3.8"

volumes:
  prometheus: {}
  alertmanager: {}
  grafana: {}

services:

  prometheus:
    volumes:
      - ./prometheus/prometheus.dev.yml:/etc/prometheus/prometheus.yml:ro
      - ./prometheus/rules.yml:/etc/prometheus/rules.yml:ro
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-public
      - traefik.http.routers.monitoring-prometheus.rule=Host(`prometheus.localhost`)

  grafana:
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-public
      - traefik.http.routers.monitoring-grafana.rule=Host(`grafana.localhost`)

  node-exporter:
    environment:
      - NODE_ID=localhost
    volumes:
      - ./node-exporter/dev-hostname:/etc/nodename
      - ./node-exporter/entrypoint.sh:/etc/node-exporter/entrypoint.sh

  alertmanager:
    volumes:
      - ./alertmanager/config.yml:/etc/alertmanager/config.yml
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-public
      - traefik.http.routers.monitoring-alertmanager.rule=Host(`alertmanager.localhost`)
