version: "3.8"

services:
  prometheus:
    image: prom/prometheus:v2.18.1
    container_name: prometheus
    # ports:
    #   - 9090:9090
    command:
      - --config.file=/etc/prometheus/prometheus.yml
#      - --web.external-url=$PROMETHEUS_WEB_EXTERNAL_URL
#      - --web.route-prefix=/prometheus/
    volumes:
      #- $PROMETHEUS_DIR:/etc/prometheus
      - prometheus:/prometheus
    configs:
      - source: prometheus-config
        target: /etc/prometheus/prometheus.yml
      - source: prometheus-rules
        target: /etc/prometheus/rules.yml
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        - traefik.http.routers.monitoring-prometheus-http.rule=Host(`prometheus.${DOMAIN?}`)
        - traefik.http.routers.monitoring-prometheus-http.entrypoints=http
        - traefik.http.routers.monitoring-prometheus-http.middlewares=https-redirect
        - traefik.http.routers.monitoring-prometheus-https.rule=Host(`prometheus.${DOMAIN?}`)
        - traefik.http.routers.monitoring-prometheus-https.entrypoints=https
        - traefik.http.routers.monitoring-prometheus-https.tls=true
        - traefik.http.routers.monitoring-prometheus-https.tls.certresolver=le
        - traefik.http.services.monitoring-prometheus.loadbalancer.server.port=9090
        - traefik.http.middlewares.monitoring-prometheus-auth.basicauth.usersfile=/run/secrets/htpasswd
        - traefik.http.routers.monitoring-prometheus-https.middlewares=monitoring-prometheus-auth
        # - traefik.http.middlewares.swarmprom-prometheus-auth.basicauth.users=${ADMIN_USER?Variable ADMIN_USER not set}:${HASHED_PASSWORD?Variable HASHED_PASSWORD not set}
        # - traefik.http.routers.swarmprom-prometheus-https.middlewares=swarmprom-prometheus-auth

    networks:
      - net
      - traefik-public

    # secrets:
    #   - htpasswd
  
  cadvisor:
    image: gcr.io/google-containers/cadvisor:v0.36.0
    container_name: cadvisor
    # ports:
    #   - 8080:8080
    command: -logtostderr -docker_only
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    deploy:
      mode: global
    networks:
      - net

  node-exporter:
    image: jbrunton/bechdel-lists-node-exporter
    build:
      context: ./node-exporter
    hostname: "myapp.{{.Task.Slot}}"
    networks:
      - net
    environment:
      - NODE_ID={{.Node.ID}}
    # ports:
    #   - 9100:9100
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
      - /etc/hostname:/etc/nodename
    command:
      - '--path.sysfs=/host/sys'
      - '--path.procfs=/host/proc'
      - '--collector.textfile.directory=/home/node-exporter/'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
      - '--no-collector.ipvs'
    # labels:
    #   - node={{ .Node.Spec.Labels.node }}
    #   - FOO=BAR
    deploy:
      mode: global
      # labels:
      #   - node={{ .Node.Spec.Labels.node }}
      #   - FOO=BAR

  grafana:
    image: jbrunton/bechdel-lists-monitoring-grafana
    container_name: grafana
    # ports:
    #   - 3000:3000
    depends_on:
      - prometheus
    networks:
      - traefik-public
    volumes:
      - grafana:/var/lib/grafana
    environment:
      - DOMAIN=$DOMAIN
    build:
      context: ./grafana
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        - traefik.http.routers.monitoring-grafana-http.rule=Host(`grafana.${DOMAIN?}`)
        - traefik.http.routers.monitoring-grafana-http.entrypoints=http
        - traefik.http.routers.monitoring-grafana-http.middlewares=https-redirect
        - traefik.http.routers.monitoring-grafana-https.rule=Host(`grafana.${DOMAIN?}`)
        - traefik.http.routers.monitoring-grafana-https.entrypoints=https
        - traefik.http.routers.monitoring-grafana-https.tls=true
        - traefik.http.routers.monitoring-grafana-https.tls.certresolver=le
        - traefik.http.services.monitoring-grafana.loadbalancer.server.port=3000
  
  alertmanager:
    image: prom/alertmanager:v0.20.0
    container_name: alertmanager
    networks:
      - traefik-public
      - net
    volumes:
      - alertmanager:/alertmanager
    command:
      - --config.file=/etc/alertmanager/config.yml
      # - --web.external-url=$ALERTMANAGER_WEB_EXTERNAL_URL
      # - --web.route-prefix=/
      - --storage.path=/alertmanager
    restart: unless-stopped
    # ports:
    #   - 9093:9093
    configs:
      - source: alertmanager-config
        target: /etc/alertmanager/config.yml
    deploy:
      mode: replicated
      replicas: 1

  # nginx:
  #   image: "nginx:1.18.0-alpine"
  #   container_name: nginx
  #   ports:
  #     - 80:80
  #     - 443:443
  #   #volumes:
  #     # - $NGINX_CERTS_DIR:/etc/nginx/certs:ro
  #     # - $NGINX_AUTH_DIR/.htpasswd:/etc/nginx/.htpasswd:ro
  #     # - $NGINX_DIR/upstreams.conf:/etc/nginx/upstreams.conf:ro
  #     # - $NGINX_DIR/services.conf:/etc/nginx/services.conf:ro
  #     # - $NGINX_DIR/$NGINX_CONF_FILE:/etc/nginx/conf.d/default.conf:ro
  #     # - $NGINX_DIR/html:/usr/share/nginx/html:ro
  #   configs:
  #     - source: nginx-upstreams-conf
  #       target: /etc/nginx/upstreams.conf
  #     - source: nginx-services-conf
  #       target: /etc/nginx/services.conf
  #     - source: nginx-default-conf
  #       target: /etc/nginx/conf.d/default.conf
  #   secrets:
  #     - htpasswd
  #     - monitoring_jbrunton_com.pem
  #     - monitoring_jbrunton_com.key
  #   depends_on:
  #     - grafana
  #     - prometheus
    
volumes:
  prometheus: {}
  alertmanager: {}
  grafana: {}

configs:
  prometheus-config:
    file: ./prometheus/prometheus.prod.yml
    name: prometheus-config-${TIMESTAMP}
  prometheus-rules:
    file: ./prometheus/rules.yml
    name: prometheus-rules-${TIMESTAMP}
  alertmanager-config:
    file: ./alertmanager/config.yml
    name: alertmanager-config-${TIMESTAMP}
  # nginx-upstreams-conf:
  #   file: ./nginx/upstreams.conf
  #   name: nginx-upstreams-conf-${TIMESTAMP}
  # nginx-services-conf:
  #   file: ./nginx/services.conf
  #   name: nginx-services-conf-${TIMESTAMP}    
  # nginx-default-conf:
  #   file: ./nginx/default.prod.conf
  #   name: nginx-default-conf-${TIMESTAMP}
  # node-exporter-entrypoint:
  #   file: ./node-exporter/entrypoint.sh
  

  monitoring_jbrunton_com.pem:
    external: true
  monitoring_jbrunton_com.key:
    external: true

networks:
  net:
    driver: overlay
  traefik-public:
    external: true