version: "3.8"

services:
  prometheus:
    image: prom/prometheus:v2.18.1
    container_name: prometheus
    ports:
      - 9090:9090
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --web.external-url=$PROMETHEUS_WEB_EXTERNAL_URL
      - --web.route-prefix=/prometheus/
    volumes:
      #- $PROMETHEUS_DIR:/etc/prometheus
      - prometheus:/prometheus
    configs:
      - source: prometheus-config
        target: /etc/prometheus/prometheus.yml
    deploy:
      mode: replicated
      replicas: 1

  cadvisor:
    image: gcr.io/google-containers/cadvisor:v0.36.0
    container_name: cadvisor
    ports:
      - 8080:8080
    command: -logtostderr -docker_only
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    deploy:
      mode: global

  node-exporter:
    image: stefanprodan/swarmprom-node-exporter:v0.16.0
    environment:
      - NODE_ID={{.Node.ID}}
    ports:
      - 9100:9100
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
      - /etc/hostname:/etc/nodename
      - ./node-exporter/entrypoint.sh:/etc/node-exporter/entrypoint.sh
    entrypoint: /etc/node-exporter/entrypoint.sh
    command:
      - '--path.sysfs=/host/sys'
      - '--path.procfs=/host/proc'
      - '--collector.textfile.directory=/etc/node-exporter/'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
      - '--no-collector.ipvs'
    # configs:
    #   - source: node-exporter-entrypoint
    #     target: /etc/node-exporter/entrypoint.sh
    deploy:
      mode: global

  grafana:
    image: jbrunton/bechdel-lists-monitoring-grafana
    container_name: grafana
    ports:
      - 3000:3000
    depends_on:
      - prometheus
    volumes:
      - grafana:/var/lib/grafana
    environment:
      - HOST_NAME=$HOST_NAME
    build:
      context: ./grafana
    deploy:
      mode: replicated
      replicas: 1

  alertmanager:
    image: prom/alertmanager:v0.20.0
    container_name: alertmanager
    volumes:
      - alertmanager:/alertmanager
    command:
      - --config.file=/etc/alertmanager/config.yml
      # - --web.external-url=$ALERTMANAGER_WEB_EXTERNAL_URL
      - --web.route-prefix=/
      - --storage.path=/alertmanager
    restart: unless-stopped
    ports:
      - 9093:9093
    configs:
      - source: alertmanager-config
        target: /etc/alertmanager/config.yml
    deploy:
      mode: replicated
      replicas: 1

  nginx:
    image: "nginx:1.18.0-alpine"
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    #volumes:
      # - $NGINX_CERTS_DIR:/etc/nginx/certs:ro
      # - $NGINX_AUTH_DIR/.htpasswd:/etc/nginx/.htpasswd:ro
      # - $NGINX_DIR/upstreams.conf:/etc/nginx/upstreams.conf:ro
      # - $NGINX_DIR/services.conf:/etc/nginx/services.conf:ro
      # - $NGINX_DIR/$NGINX_CONF_FILE:/etc/nginx/conf.d/default.conf:ro
      # - $NGINX_DIR/html:/usr/share/nginx/html:ro
    configs:
      - source: nginx-upstreams-conf
        target: /etc/nginx/upstreams.conf
      - source: nginx-services-conf
        target: /etc/nginx/services.conf
      - source: nginx-default-conf
        target: /etc/nginx/conf.d/default.conf
    secrets:
      - htpasswd
      - monitoring_jbrunton_com.pem
      - monitoring_jbrunton_com.key
    depends_on:
      - grafana
      - prometheus
    
volumes:
  prometheus: {}
  alertmanager: {}
  grafana: {}

configs:
  prometheus-config:
    file: ./prometheus/prometheus.dev.yml
    name: prometheus-config-${TIMESTAMP}
  alertmanager-config:
    file: ./alertmanager/config.yml
    name: alertmanager-config-${TIMESTAMP}
  nginx-upstreams-conf:
    file: ./nginx/upstreams.conf
    name: nginx-upstreams-conf-${TIMESTAMP}
  nginx-services-conf:
    file: ./nginx/services.conf
    name: nginx-services-conf-${TIMESTAMP}    
  nginx-default-conf:
    file: ./nginx/default.prod.conf
    name: nginx-default-conf-${TIMESTAMP}
  node-exporter-entrypoint:
    file: ./node-exporter/entrypoint.sh
  
secrets:
  htpasswd:
    file: ./nginx/.htpasswd
  monitoring_jbrunton_com.pem:
    external: true
  monitoring_jbrunton_com.key:
    external: true
    