version: "3.8"

services:
  prometheus:
    image: prom/prometheus:v2.18.1
    container_name: prometheus
    ports:
      - 9090:9090
    command:
      - --config.file=/etc/prometheus/prometheus.yml
#      - --web.external-url=$PROMETHEUS_WEB_EXTERNAL_URL
#      - --web.route-prefix=/prometheus/
    volumes:
      #- $PROMETHEUS_DIR:/etc/prometheus
      - prometheus:/prometheus
    configs:
      - source: prometheus-config
        target: /etc/prometheus/prometheus.yml
    deploy:
      mode: replicated
      replicas: 1

  cadvisor:
    image: gcr.io/google-containers/cadvisor:v0.36.0
    container_name: cadvisor
    ports:
      - 8080:8080
    command: -logtostderr -docker_only
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    deploy:
      mode: global

  node-exporter:
    image: stefanprodan/swarmprom-node-exporter:v0.16.0
    environment:
      - NODE_ID={{.Node.ID}}
    ports:
      - 9100:9100
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
      - /etc/hostname:/etc/nodename
    command:
      - '--path.sysfs=/host/sys'
      - '--path.procfs=/host/proc'
      - '--collector.textfile.directory=/etc/node-exporter/'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
      - '--no-collector.ipvs'
    deploy:
      mode: global

  grafana:
    image: grafana/grafana:7.0.0
    container_name: grafana
    ports:
      - 3000:3000
    depends_on:
      - prometheus
    volumes:
      #- $GRAFANA_DIR/$GRAFANA_INI_FILE:/etc/grafana/grafana.ini
      #- $GRAFANA_DIR/provisioning:/etc/grafana/provisioning/
      - grafana:/var/lib/grafana
    configs:
      # - source: grafana-config
      #   target: /etc/grafana/grafana.ini
      - source: grafana-datasource
        target: /etc/grafana/provisioning/datasources/prometheus.yml
    deploy:
      mode: replicated
      replicas: 1

  alertmanager:
    image: prom/alertmanager:v0.20.0
    container_name: alertmanager
    volumes:
      - alertmanager:/alertmanager
    command:
      - --config.file=/etc/alertmanager/config.yml
      # - --web.external-url=$ALERTMANAGER_WEB_EXTERNAL_URL
      - --web.route-prefix=/
      - --storage.path=/alertmanager
    restart: unless-stopped
    ports:
      - 9093:9093
    configs:
      - source: alertmanager-config
        target: /etc/alertmanager/config.yml
    deploy:
      mode: replicated
      replicas: 1
    
volumes:
  prometheus: {}
  alertmanager: {}
  grafana: {}

configs:
  prometheus-config:
    file: ./prometheus/prometheus.prod.yml
    name: prometheus-config-${TIMESTAMP}
  alertmanager-config:
    file: ./alertmanager/config.yml
    name: alertmanager-config-${TIMESTAMP}
  grafana-datasource:
    file: ./grafana/datasources/prometheus.yml
    name: grafana-datasource-${TIMESTAMP}
