version: "3.8"

services:

  prometheus:
    volumes:
      - ./prometheus/prometheus.dev.yml:/etc/prometheus/prometheus.yml:ro

  grafana:
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning/

  node-exporter:
    volumes:
      - ./node-exporter/dev-hostname:/etc/nodename

  alertmanager:
    volumes:
      - ./alertmanager/config.yml:/etc/alertmanager/config.yml

  nginx:
    volumes:
      #- $NGINX_CERTS_DIR:/etc/nginx/certs:ro
      #- $NGINX_AUTH_DIR/.htpasswd:/etc/nginx/.htpasswd:ro
      - ./nginx/upstreams.conf:/etc/nginx/upstreams.conf:ro
      - ./nginx/services.conf:/etc/nginx/services.conf:ro
      - ./nginx/default.dev.conf:/etc/nginx/conf.d/default.conf:ro
