version: "3.8"

services:

  prometheus:
    volumes:
      - ./prometheus/prometheus.dev.yml:/etc/prometheus/prometheus.yml:ro
      - ./prometheus/rules.yml:/etc/prometheus/rules.yml:ro
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-public
      - traefik.http.routers.monitoring-prometheus.rule=Host(`prometheus.${DOMAIN?}`)


  grafana:
    environment:
      - DOMAIN=localhost
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-public
      - traefik.http.routers.monitoring-grafana.rule=Host(`grafana.${DOMAIN?}`)

  
  node-exporter:
    volumes:
      - ./node-exporter/dev-hostname:/etc/nodename
      - ./node-exporter/entrypoint.sh:/etc/node-exporter/entrypoint.sh

  alertmanager:
    volumes:
      - ./alertmanager/config.yml:/etc/alertmanager/config.yml
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-public
      - traefik.http.routers.monitoring-alertmanager.rule=Host(`alertmanager.${DOMAIN?}`)
