version: "3.3"

services:
  prometheus:
    image: prom/prometheus:v2.18.1
    container_name: prometheus
    ports:
      - 9090:9090
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --web.external-url=$PROMETHEUS_WEB_EXTERNAL_URL
      - --web.route-prefix=/prometheus/
    volumes:
      - $PROMETHEUS_DIR:/etc/prometheus
      - prometheus:/prometheus
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
          
  cadvisor:
    image: gcr.io/google-containers/cadvisor:v0.36.0
    container_name: cadvisor
    ports:
      - 8080:8080
    command: -logtostderr -docker_only
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    deploy:
      mode: global
volumes:
  prometheus: {}
