{
 "title": "Apps Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": "up{job=\"api\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "Active Alerts",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count by (alertstate,alertname,instance) (ALERTS{instance=~\"$instance\",group=\"app\"})",
     "legendFormat": "{{ alertname }} {{ alertstate }}"
    }
   ]
  },
  {
   "title": "Alert History",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(ALERTS{instance=~\"$instance\",alertstate=\"pending\",group=\"app\"})",
     "legendFormat": "pending"
    },
    {
     "expr": "sum(ALERTS{instance=~\"$instance\",alertstate=\"firing\",group=\"app\"})",
     "legendFormat": "firing"
    }
   ]
  },
  { "title": "Alerts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  { "title": "Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "API Throughput",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "http:throughput:mean1m{instance=~\"$instance\"}\n",
     "legendFormat": "{{ path }}"
    }
   ]
  },
  {
   "title": "API Latency",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "http:latency:mean1m{instance=~\"$instance\"}",
     "legendFormat": "{{ path }}"
    }
   ]
  },
  {
   "title": "Traefik Throughput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum(traefik:throughput:mean1m)" }
   ]
  },
  {
   "title": "API Error Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "http:errors:mean1m", "legendFormat": "{{ path }}" }
   ]
  }
 ]
}