{
 "title": "Docker and Host Monitoring",
 "description": "Docker Monitoring Template",
 "tags": [
  "docker",
  "prometheus, ",
  "node-exporter",
  "cadvisor"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "node_name", "query": "node_meta" }
  ]
 },
 "panels": [
  { "title": "Alerts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Active Alerts",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count by (alertstate,alertname,node_name) (ALERTS{node_name=~\"$node_name\",group=\"node\"})",
     "legendFormat": "{{ alertname }} {{ alertstate }}"
    }
   ]
  },
  {
   "title": "Alert History",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(ALERTS{node_name=~\"$node_name\",alertstate=\"pending\",group=\"node\"})",
     "legendFormat": "pending"
    },
    {
     "expr": "sum(ALERTS{node_name=~\"$node_name\",alertstate=\"firing\",group=\"node\"})",
     "legendFormat": "firing"
    }
   ]
  },
  { "title": "Host", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "node:cpu_usage:mean1m{node_name=~\"$node_name\"}"
    }
   ]
  },
  {
   "title": "Avg CPU",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "node:cpu_usage:mean1m{node_name=~\"$node_name\"}"
    }
   ]
  },
  {
   "title": "Mem Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "node:mem_usage:mean1m{node_name=~\"$node_name\"}"
    }
   ]
  },
  {
   "title": "Avg Mem",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "node:mem_usage:mean1m{node_name=~\"$node_name\"}"
    }
   ]
  },
  {
   "title": "FS Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "node:fs_usage:mean1m{node_name=~\"$node_name\"}"
    }
   ]
  },
  {
   "title": "FS Change",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "expr": "node:fs_usage:mean1m{node_name=~\"$node_name\"}"
    }
   ]
  },
  {
   "title": "Avg Sent",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(node_network_transmit_bytes_total{node_name=~\"$node_name\"}[1m]))"
    }
   ]
  },
  {
   "title": "Avg Received",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total{node_name=~\"$node_name\"}[1m]))"
    }
   ]
  },
  {
   "title": "Max CPU",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "node:cpu_usage:mean1m{node_name=~\"$node_name\"}"
    }
   ]
  },
  {
   "title": "Max Mem",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "node:mem_usage:mean1m{node_name=~\"$node_name\"}"
    }
   ]
  },
  {
   "title": "Max Sent",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(rate(node_network_transmit_bytes_total{node_name=~\"$node_name\"}[1m]))"
    }
   ]
  },
  {
   "title": "Max Received",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total{node_name=~\"$node_name\"}[1m]))"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node:cpu_usage:mean1m{node_name=~\"$node_name\"}",
     "legendFormat": "% Used"
    }
   ]
  },
  {
   "title": "Mem Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 13 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "node:mem_usage:mean1m{node_name=~\"$node_name\"}",
     "legendFormat": "% Available"
    }
   ]
  },
  {
   "title": "FS Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "node:fs_usage:mean1m{node_name=~\"$node_name\"}",
     "legendFormat": "% Used"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "graph",
   "gridPos": { "h": 14, "w": 6, "x": 18, "y": 13 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total{node_name=~\"$node_name\"}[1m]))",
     "legendFormat": "Receive"
    },
    {
     "expr": "- sum(rate(node_network_transmit_bytes_total{node_name=~\"$node_name\"}[1m]))",
     "legendFormat": "Transmit"
    }
   ]
  },
  {
   "title": "CPU Modes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(node_cpu_seconds_total{node_name=~\"$node_name\",mode!=\"idle\"} [1m]) * 100",
     "legendFormat": "{{ mode }}"
    },
    {
     "expr": "rate(node_cpu_seconds_total{node_name=~\"$node_name\",mode=\"idle\"} [1m]) * 100",
     "legendFormat": "idle"
    }
   ]
  },
  {
   "title": "Mem Available",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 19 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{node_name=~\"$node_name\"} - node_memory_MemAvailable_bytes{node_name=~\"$node_name\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "node_memory_MemAvailable_bytes{node_name=~\"$node_name\"}",
     "legendFormat": "Available"
    }
   ]
  },
  {
   "title": "FS Available",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(node_filesystem_size_bytes{node_name=~\"$node_name\"} - node_filesystem_avail_bytes{node_name=~\"$node_name\"})",
     "legendFormat": "Used"
    },
    {
     "expr": "sum(node_filesystem_avail_bytes{node_name=~\"$node_name\"})",
     "legendFormat": "Available"
    }
   ]
  },
  { "title": "Container Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Container CPU usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(container_cpu_system_seconds_total{image!=\"\",node_name=~\"$node_name\"}[1m])",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Container Memory Usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 28 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_max_usage_bytes{image!=\"\",node_name=~\"$node_name\"}",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Container Network Input",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sort_desc(sum by (name) (rate(container_network_receive_bytes_total{image!=\"\",node_name=~\"$node_name\"}[1m] ) ))",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Container Network Output",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 28 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (name) (rate(container_network_receive_bytes_total{image!=\"\",node_name=~\"$node_name\"}[1m] ) )",
     "legendFormat": "{{ name }}"
    }
   ]
  }
 ]
}